<?php

use Illuminate\Database\Seeder;

class SentenceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->sentences as $sentence) {
            DB::table('sentences')->insert([
                'type' => $sentence['type'],
                'text' => $sentence['text'],
                'word_count' => str_word_count($sentence['text']),
            ]);
        }
    }

    protected $sentences = [
        ['type' => 'beginning', 'text' => 'A glowing performance this evening'],
        ['type' => 'beginning', 'text' => 'A stellar performance this evening'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s performance was a strong one'],
        ['type' => 'beginning', 'text' => 'Tonight was a low energy performance, though we did seem to pick up steam towards the end'],
        ['type' => 'beginning', 'text' => 'Our final performance was a strong one &ndash; slow energy to start, but it picked up rapidly'],
        ['type' => 'beginning', 'text' => 'A good night for our first preview'],
        ['type' => 'beginning', 'text' => 'Energy was high for our opening night performance &ndash; it was a spectacular show'],
        ['type' => 'beginning', 'text' => 'Energy was high tonight, and the audience response was strong &ndash; we continue to tighten scene work and transitions'],
        ['type' => 'beginning', 'text' => 'Our final performance went well &ndash; energy was strong and an audience of friends and family lent for great response from the house'],
        ['type' => 'beginning', 'text' => 'Another good show this afternoon, though the audience response was nowhere near as strong as it was last night'],
        ['type' => 'beginning', 'text' => 'The show had renewed energy after these last few days off'],
        ['type' => 'beginning', 'text' => 'We had a solid show this evening'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo; s opening performance was a strong one &ndash; energy was high and the audience reaction was very strong and favorable'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s preview performance was a solid one &ndash; the audience seemed very receptive and enthusiastic'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s preview performance was a solid one &ndash; a smaller audience than yesterday, but still a very positive reaction'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s opening night performance was a very strong one &ndash; the cast was very energetic, and the enthusiasm from the audience was very palpable'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s performance was less energetic than last night, but still on-point and kinetic'],
        ['type' => 'beginning', 'text' => 'This afternoon&rsquo;s matinee performance was very solid &ndash; we had a bigger house than last night, but the energy from the patrons during the show was about the same'],
        ['type' => 'beginning', 'text' => 'After two days off it took us a while to get back into the flow of the show'],
        ['type' => 'beginning', 'text' => 'This afternoon&rsquo;s matinee was a strong one &ndash; the energy of the performers was back up to its usual level and there were no troubles with the lines as there were last night'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s performance was extremely positive!'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s performance was fantastic'],
        ['type' => 'beginning', 'text' => 'This evening&rsquo;s performance was solid, though we did have some more trouble with lines in a couple places'],
        ['type' => 'beginning', 'text' => 'This evening&rsquo;s performance was a strong one; we were able to get into the groove of the show without much difficulty'],
        ['type' => 'beginning', 'text' => 'This evening&rsquo;s show was good &ndash; the audience was slow to respond at first, but by the end of the first act, they were eating out of our hands'],
        ['type' => 'beginning', 'text' => 'This evening&rsquo;s show was very solid &ndash; the audience seemed to really be into the story, and the response at the end of the play was very strong, once again'],
        ['type' => 'beginning', 'text' => 'Mr &#46; [last-name] was unable to go on for this performance; his understudy, Mr&#46; [last-name], went on for him instead'],
        ['type' => 'beginning', 'text' => 'Our final performance was a fantastic one'],
        ['type' => 'beginning', 'text' => 'Mr &#46; [last-name] was with us again at this performance'],
        ['type' => 'beginning', 'text' => 'The Show tonight was strong, but slightly distracted'],
        ['type' => 'beginning', 'text' => 'This evening&rsquo;s performance was a fantastic one &ndash; energy was extremely high, and the audience response was overwhelmingly enthusiastic'],
        ['type' => 'beginning', 'text' => 'This evening&rsquo;s performance was much better received than our matinee'],
        ['type' => 'beginning', 'text' => 'Our matinee today was not a strong one'],
        ['type' => 'beginning', 'text' => 'Our opening night performance was a stellar one &ndash; the audience was fantastic and the overall energy was as high as we have ever seen it'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s performance was lacking in its usual energy'],
        ['type' => 'beginning', 'text' => 'This evening&rsquo;s performance was firmly solid'],
        ['type' => 'beginning', 'text' => 'Attendance was low again tonight, but they were extremely focused'],
        ['type' => 'beginning', 'text' => 'Our last show of the week was solid &ndash; not as tight as we have seen it, but still solid'],
        ['type' => 'beginning', 'text' => 'A good audience tonight &ndash; slightly bigger than we saw last week'],
        ['type' => 'beginning', 'text' => 'Another good house tonight &ndash; the main seating bank was mostly filled, but the sides were empty'],
        ['type' => 'beginning', 'text' => 'A lovely performance this evening, a large house with lots of laughs(and giggling) informed by a strong and vigorous performance on the part of the actors'],
        ['type' => 'beginning', 'text' => 'A large house for our matinee performance this afternoon'],
        ['type' => 'beginning', 'text' => 'Another large house for our matinee today'],
        ['type' => 'beginning', 'text' => 'After all the craziness yesterday, it was good to be back to our normal routine'],
        ['type' => 'beginning', 'text' => 'Our rythym was a bit askew tonight, but we still managed to hit our stride'],
        ['type' => 'beginning', 'text' => 'Another strong performance this evening &ndash; there were a couple of small stumbles in the text & amp; music, but nothing that the audience was able to notice'],
        ['type' => 'beginning', 'text' => 'Tonight&rsquo;s performance was terrific &ndash; we wrapped things up on an excellent note'],
        ['type' => 'beginning', 'text' => 'Our matinee today was a bit squeaky, but still very solid'],
        ['type' => 'middle', 'text' => 'The energy and synchronicity that we have seen before returned with full force'],
        ['type' => 'middle', 'text' => 'Everyone was very alive and present'],
        ['type' => 'middle', 'text' => 'Great audience this evening'],
        ['type' => 'middle', 'text' => 'They were with us from beginning to end and did not hold back when they found something funny'],
        ['type' => 'middle', 'text' => 'The audience was subdued but still very engaged'],
        ['type' => 'middle', 'text' => 'Very high enthusiasm and energy from all'],
        ['type' => 'middle', 'text' => 'Energy remained high after our opening night'],
        ['type' => 'middle', 'text' => 'Some of the timing was not as strong as it has been, both onstage and in the booth'],
        ['type' => 'middle', 'text' => 'The audience reaction was strong and encouraging'],
        ['type' => 'middle', 'text' => 'Today we accidentally sent the bed off the side of the platform during a scene change - the noise was masked but still noticeable'],
        ['type' => 'middle', 'text' => 'Our intermission was delayed briefly due to a cabling issue under the main wagon'],
        ['type' => 'middle', 'text' => 'The pace was tight'],
        ['type' => 'middle', 'text' => 'The audience was responsive throughout the show'],
        ['type' => 'middle', 'text' => 'There were some complaints from audience members about stuffiness at the intermission, and house management opened the doors to let some air in'],
        ['type' => 'middle', 'text' => 'We did receive some standing ovations at the end of the show'],
        ['type' => 'middle', 'text' => 'It did not help that the house was relatively small'],
        ['type' => 'middle', 'text' => 'Energy and timing were a bit off, which led to a blurring of certain important moments'],
        ['type' => 'middle', 'text' => 'Energy was high, and the audience response was very strong'],
        ['type' => 'middle', 'text' => 'There was a 3/4 standing ovation during the curtain call'],
        ['type' => 'middle', 'text' => 'The audience response was extremely positive, as usual'],
        ['type' => 'middle', 'text' => 'We had a put-in rehearsal prior to fight call to review the scenes in question with the company and made some minor tweaks to the show to ease his incorporation into the show. Nothing major was altered'],
        ['type' => 'middle', 'text' => 'We ended our run on a very high note &ndash; positive energy was exuding from everyone, and we had one of our largest houses ever'],
        ['type' => 'middle', 'text' => 'Audience response was really quite strong'],
        ['type' => 'middle', 'text' => 'The smoothness and tightness that we saw last night was not quite there, but energy was still high'],
        ['type' => 'middle', 'text' => 'All involved seemed to have a great time'],
        ['type' => 'middle', 'text' => 'We performed the show without an intermission tonight as an experiment, and it seemed to go very well'],
        ['type' => 'middle', 'text' => 'The audience was minimal, and their energy was non - existent, which lead to flagging energy in the cast'],
        ['type' => 'middle', 'text' => 'It was also our first performance with Mr&#46; [last-name] covering Mr&#46; [last-name]&rsquo;s role'],
        ['type' => 'middle', 'text' => 'The house was relatively small, but the enthusiasm from them was still very strong'],
        ['type' => 'middle', 'text' => 'The cast seemed to be enjoying themselves quite a bit during the performance'],
        ['type' => 'middle', 'text' => 'The audience was small but attentive and enthusiastic'],
        ['type' => 'middle', 'text' => 'Mr&#46; [last-name] is still being careful with his knee, so we have continued to use the alternative fight blocking'],
        ['type' => 'middle', 'text' => 'Reactions were strong and favorable'],
        ['type' => 'middle', 'text' => 'The performance was solid and reliable'],
        ['type' => 'middle', 'text' => 'We had a pretty big house, and they seemed to be very intently focused on the work'],
        ['type' => 'middle', 'text' => 'We tripped over some text, but it was not noticeable to the audience'],
        ['type' => 'middle', 'text' => 'The cast received warm applause and cheers at curtain call'],
        ['type' => 'middle', 'text' => 'There was a partial standing ovation during curtain call'],
        ['type' => 'middle', 'text' => 'The audience seemed very receptive, and was glowing with praise afterwards'],
        ['type' => 'middle', 'text' => 'The only noticeable problem was a severely delayed light cues at the end of the show, which will be rectified for the next performance'],
        ['type' => 'middle', 'text' => 'The audience was much more subdued than the ones we &rsquo;ve had previously'],
        ['type' => 'middle', 'text' => 'A strong, responsive audience was a help'],
        ['type' => 'middle', 'text' => 'Everyone agreed that it was good to be in front of an audience for the first time'],
        ['type' => 'middle', 'text' => 'The show itself ran smoothly, except for one prematurely fired light cue which interrupted the second scene'],
        ['type' => 'middle', 'text' => 'The coffin was late in entering Act IV, Scene 2'],
        ['type' => 'middle', 'text' => 'The show flowed smoothly from start to end'],
        ['type' => 'middle', 'text' => 'Ms&#46; [last-name] was late for her entrance in scene 5 &ndash; the other actors on stage were able to vamp, and the delay was only slightly noticeable'],
        ['type' => 'end', 'text' => 'The cast received warm applause at curain call'],
        ['type' => 'end', 'text' => 'We had a responsive audience tonight - their enthusistic applause lingered'],
        ['type' => 'end', 'text' => 'I think everyone was excited to have an audience in the house for the first time'],
        ['type' => 'end', 'text' => 'Our late start was due to two patrons in the house who were taking photos'],
        ['type' => 'end', 'text' => 'We are gearing up for tomorrow&rsquo;s opening'],
        ['type' => 'end', 'text' => 'About 10 minutes into act 2, one of the on-stage speakers popped loudly &ndash; it was slightly distracting, but it only happened that one time'],
        ['type' => 'end', 'text' => 'The audience was much more subdued and quiet than we have seen in the past'],
        ['type' => 'end', 'text' => 'This afternoon&rsquo;s performance served as a dress rehearsal for the audio describers who will be describing next Saturday&rsquo;s matinee performance'],
        ['type' => 'end', 'text' => 'There were several moments towards the beginning where some dialogue was flubbed a bit - we will be reviewing those lines before tomorrow night&rsquo;s show'],
        ['type' => 'end', 'text' => 'I have a feeling that after some rest we will be ready to attack our next with our usual ferocity'],
        ['type' => 'end', 'text' => 'The audience was relatively quiet during the course of the show, but the response during the curtain call was very, very strong'],
        ['type' => 'end', 'text' => 'We got a late start due to several last minute walk-ups at the box office'],
        ['type' => 'end', 'text' => 'The overall arch of the evening was not hindered though, and the audience reacted very favorably at the end of the night'],
        ['type' => 'end', 'text' => 'Our prop runner, [first-name], was out sick today - [first-name] and [first-name] covered for her back stage'],
        ['type' => 'end', 'text' => 'Once again, audience reaction was strong and favorable'],
        ['type' => 'end', 'text' => 'The start of Act 2 was delayed due to slow-moving patrons'],
        ['type' => 'end', 'text' => 'The show was very strong, and the audience reaction was very favorable'],
        ['type' => 'end', 'text' => 'Mr&#46; [last-name] was 15 minutes late to this afternoon&rsquo;s rehearsal, due to transportation issues'],
        ['type' => 'end', 'text' => 'Ms&#46; [last-name] was 10 minutes late to this afternoon&rsquo;s rehearsal call'],
        ['type' => 'end', 'text' => 'The audience was not as vocal as we have seen, but there was still a solid response'],
        ['type' => 'end', 'text' => 'Ms&#46; [last-name] was 10 minutes late to this afternoon&rsquo;s call'],
        ['type' => 'end', 'text' => 'Most all of the actors mentioned to me that they felt it was one of our best performances yet'],
        ['type' => 'end', 'text' => 'A small house combined with the day off yesterday made for a show with mixed energy'],
        ['type' => 'end', 'text' => 'Mr&#46; [last-name] injured his left knee during the fight in act three'],
        ['type' => 'end', 'text' => 'The performance was very strong and fully committed'],
        ['type' => 'end', 'text' => 'Mr&#46; [last-name] will be in on Tuesday to shadow Mr&#46; [last-name] backstage, in anticipation of the upcoming crew replacement'],
        ['type' => 'end', 'text' => 'Some of the vocals were a bit wobbly tonight, but that was mostly due to the day off &ndash; we should be back in good shape tomorrow'],
        ['type' => 'end', 'text' => 'A strong &amp; solid performance by all'],
        ['type' => 'end', 'text' => 'Ms&#46; [last-name] has mentioned that her left foot has been bothering her for the last week or so, she feels that it may have something to do with her footwear'],
        ['type' => 'end', 'text' => 'Lots of chuckles throughout'],
        ['type' => 'end', 'text' => 'It was an excellent show - very solid, with a lot of laughs &amp; applause from the audience'],
        ['type' => 'end', 'text' => 'The performance was strong and energetic, as always'],
        ['type' => 'end', 'text' => 'The house was pretty big, and there was a lot of positive response'],
        ['type' => 'end', 'text' => 'Lots of laughs throughout the show, and very strong applause at the end'],
        ['type' => 'end', 'text' => 'The (large) audience seemed to enjoy it very much &ndash; there were lots of laughs and the applause at the end was very strong'],
        ['type' => 'end', 'text' => 'Audience response was strong and favorable'],

    ];
}
